import React, { useState, useEffect } from 'react';
import { ProgramEntry, GenerateSummaryResponse, ProgramType } from '../types';
import { getEntries, removeEntry, toggleComplete, clearEntries, addEntry } from '../services/storageService';
import { generatePrayerSchedule, organizeItemsSmartly } from '../services/geminiService';
import { PROGRAM_OPTIONS } from '../constants';

const AdminDashboard: React.FC = () => {
  const [entries, setEntries] = useState<ProgramEntry[]>([]);
  const [summary, setSummary] = useState<GenerateSummaryResponse | null>(null);
  const [isLoadingAI, setIsLoadingAI] = useState(false);
  const [isOrganizing, setIsOrganizing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Check for essential program parts
  const hasStartPrayer = entries.some(e => e.type === ProgramType.START_PRAYER);
  const hasEndPrayer = entries.some(e => e.type === ProgramType.END_PRAYER);
  const isProgramComplete = hasStartPrayer && hasEndPrayer;

  // Polling to simulate real-time updates since we are using LocalStorage
  useEffect(() => {
    const load = () => setEntries(getEntries());
    load();
    const interval = setInterval(load, 3000);
    return () => clearInterval(interval);
  }, []);

  const handleDelete = (id: string) => {
    setEntries(removeEntry(id));
  };

  const handleToggle = (id: string) => {
    setEntries(toggleComplete(id));
  };

  const handleClear = () => {
    if (confirm("Are you sure you want to clear all entries? This cannot be undone.")) {
      clearEntries();
      setEntries([]);
      setSummary(null);
    }
  };

  const handleGenerateReport = async () => {
    if (entries.length === 0) {
        setError("No entries to report on.");
        return;
    }
    if (!isProgramComplete) {
        setError("Please wait for Start and End prayers to be submitted.");
        return;
    }

    setIsLoadingAI(true);
    setError(null);
    try {
      const jsonString = await generatePrayerSchedule(entries);
      if (jsonString) {
        const parsed = JSON.parse(jsonString);
        setSummary(parsed);
      }
    } catch (e) {
      setError("Failed to generate AI report. Please check API key.");
    } finally {
      setIsLoadingAI(false);
    }
  };

  const handleAutoOrganize = async () => {
     if (entries.length === 0) return;
     setIsOrganizing(true);
     try {
         const jsonStr = await organizeItemsSmartly(entries);
         if(jsonStr) {
             const organized: ProgramEntry[] = JSON.parse(jsonStr);
             // We need to update storage with this new order. 
             // Since storage is append-only in our simple implementation, we cheat by clearing and adding.
             clearEntries();
             organized.forEach(e => addEntry(e));
             setEntries(organized);
         }
     } catch (e) {
         setError("Failed to organize items.");
     } finally {
         setIsOrganizing(false);
     }
  }

  const handleShareWhatsApp = () => {
    if (!summary) return;

    const text = `*✝️ Prayer Service Report ✝️*

*🗣️ Opening Speech:*
${summary.openingSpeech}

*📋 Agenda Summary:*
${summary.agendaSummary}

*🙏 Closing Remarks:*
${summary.closingRemarks}

_Generated by PrayerFlow_`;

    const url = `https://wa.me/?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  const getIcon = (type: string) => {
    return PROGRAM_OPTIONS.find(p => p.value === type)?.icon || '📌';
  };

  return (
    <div className="space-y-8">
      {/* Header Controls */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white p-4 rounded-xl border border-church-200 shadow-sm">
        <div>
            <h2 className="text-2xl font-serif font-bold text-church-900">Dashboard</h2>
            <div className="flex items-center gap-2 text-sm">
              <span className="text-church-500">{entries.length} items in queue</span>
              {!isProgramComplete && (
                <span className="text-orange-500 bg-orange-50 px-2 py-0.5 rounded text-xs font-medium">
                  Waiting for Start/End Prayer
                </span>
              )}
            </div>
        </div>
        <div className="flex flex-wrap gap-2">
          <button 
            onClick={handleAutoOrganize}
            disabled={isOrganizing || entries.length === 0}
            className="px-4 py-2 bg-church-100 text-church-700 rounded-lg hover:bg-church-200 font-medium transition-colors text-sm disabled:opacity-50"
          >
             {isOrganizing ? 'Organizing...' : '✨ Auto-Sort List'}
          </button>
          <button 
            onClick={handleGenerateReport}
            disabled={isLoadingAI || entries.length === 0 || !isProgramComplete}
            title={!isProgramComplete ? "Start Prayer and End Prayer are required" : "Generate AI Leader's Guide"}
            className={`px-4 py-2 rounded-lg font-medium transition-colors text-sm flex items-center ${
              !isProgramComplete 
                ? 'bg-gray-100 text-gray-400 cursor-not-allowed' 
                : 'bg-purple-100 text-purple-700 hover:bg-purple-200'
            }`}
          >
            {isLoadingAI ? (
                 <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-purple-700" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                 </svg>
            ) : !isProgramComplete ? (
                 '⏳ Waiting for Complete Program'
            ) : (
                 '🤖 Guide Me (AI)'
            )}
          </button>
          <button 
            onClick={handleClear}
            className="px-4 py-2 bg-red-50 text-red-600 rounded-lg hover:bg-red-100 font-medium transition-colors text-sm"
          >
            Clear All
          </button>
        </div>
      </div>

      {error && (
          <div className="bg-red-50 border-l-4 border-red-400 p-4 rounded-r-lg">
            <p className="text-red-700 text-sm">{error}</p>
          </div>
      )}

      <div className="grid lg:grid-cols-3 gap-8">
        {/* Left Column: The List */}
        <div className="lg:col-span-2 space-y-4">
          {entries.length === 0 ? (
            <div className="text-center py-12 bg-white rounded-xl border border-dashed border-church-300 text-church-400">
              No program items submitted yet.
            </div>
          ) : (
            entries.map((entry, idx) => (
              <div 
                key={entry.id}
                className={`relative group bg-white p-4 rounded-lg shadow-sm border transition-all duration-200 ${
                  entry.completed ? 'border-green-200 bg-green-50 opacity-70' : 'border-church-100 hover:border-church-300 hover:shadow-md'
                }`}
              >
                <div className="flex items-start justify-between">
                    <div className="flex items-start gap-4">
                         <div className="flex-shrink-0 w-8 h-8 bg-church-50 rounded-full flex items-center justify-center text-lg">
                             {getIcon(entry.type)}
                         </div>
                         <div>
                            <div className="flex items-center gap-2 mb-1">
                                <span className="text-xs font-bold uppercase tracking-wider text-church-500 bg-church-50 px-2 py-0.5 rounded">
                                    {entry.type}
                                </span>
                                <span className="text-xs text-gray-400">#{idx + 1}</span>
                            </div>
                            <h3 className={`font-serif font-medium text-lg ${entry.completed ? 'line-through text-gray-500' : 'text-church-900'}`}>
                                {entry.personName}
                            </h3>
                            <p className="text-church-600 mt-1 text-sm">{entry.details}</p>
                         </div>
                    </div>

                    <div className="flex flex-col gap-2">
                        <button 
                            onClick={() => handleToggle(entry.id)}
                            className={`p-2 rounded-full transition-colors ${entry.completed ? 'text-green-600 bg-green-100' : 'text-gray-300 hover:bg-green-50 hover:text-green-500'}`}
                            title={entry.completed ? "Mark Incomplete" : "Mark Complete"}
                        >
                            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
                        </button>
                        <button 
                            onClick={() => handleDelete(entry.id)}
                            className="p-2 rounded-full text-gray-300 hover:bg-red-50 hover:text-red-500 transition-colors"
                            title="Remove"
                        >
                            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" /></svg>
                        </button>
                    </div>
                </div>
              </div>
            ))
          )}
        </div>

        {/* Right Column: AI Report */}
        <div className="lg:col-span-1">
            {summary ? (
                <div className="bg-white rounded-xl shadow-lg border border-purple-100 overflow-hidden sticky top-6">
                    <div className="bg-gradient-to-r from-purple-600 to-church-600 p-4 flex justify-between items-center">
                        <h3 className="text-white font-serif font-bold text-lg flex items-center">
                            <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" /></svg>
                            Leader's Guide
                        </h3>
                        <button 
                            onClick={handleShareWhatsApp}
                            className="text-white/90 hover:text-white hover:bg-white/20 p-1.5 rounded-lg transition-colors"
                            title="Share on WhatsApp"
                        >
                           <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                               <path d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.587-5.946.003-6.556 5.338-11.891 11.893-11.891 3.181.001 6.167 1.24 8.413 3.488 2.245 2.248 3.481 5.236 3.48 8.414-.003 6.557-5.338 11.892-11.893 11.892-1.99-.001-3.951-.5-5.688-1.448l-6.305 1.654zm6.597-3.807c1.676.995 3.276 1.591 5.392 1.592 5.448 0 9.886-4.434 9.889-9.885.002-5.462-4.415-9.89-9.881-9.892-5.452 0-9.887 4.434-9.889 9.884-.001 2.225.651 3.891 1.746 5.634l-.999 3.648 3.742-.981zm11.387-5.464c-.074-.124-.272-.198-.57-.347-.297-.149-1.758-.868-2.031-.967-.272-.099-.47-.149-.669.149-.198.297-.768.967-.941 1.165-.173.198-.347.223-.644.074-.297-.149-1.255-.462-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.297-.347.446-.521.151-.172.2-.296.3-.495.099-.198.05-.372-.025-.521-.075-.148-.669-1.611-.916-2.206-.242-.579-.487-.501-.669-.51l-.57-.01c-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.095 3.2 5.076 4.487.709.306 1.263.489 1.694.626.712.226 1.36.194 1.872.118.571-.085 1.758-.719 2.006-1.413.248-.695.248-1.29.173-1.414z"/>
                           </svg>
                        </button>
                    </div>
                    <div className="p-6 space-y-6 overflow-y-auto max-h-[80vh]">
                        
                        <div>
                            <h4 className="text-xs font-bold text-church-400 uppercase tracking-widest mb-2">Opening</h4>
                            <div className="bg-purple-50 p-3 rounded-lg text-church-800 text-sm leading-relaxed italic">
                                "{summary.openingSpeech}"
                            </div>
                        </div>

                        <div>
                            <h4 className="text-xs font-bold text-church-400 uppercase tracking-widest mb-2">Agenda Summary</h4>
                            <div className="prose prose-sm text-church-700 whitespace-pre-line">
                                {summary.agendaSummary}
                            </div>
                        </div>

                        <div>
                            <h4 className="text-xs font-bold text-church-400 uppercase tracking-widest mb-2">Closing</h4>
                            <div className="bg-church-50 p-3 rounded-lg text-church-800 text-sm leading-relaxed italic">
                                "{summary.closingRemarks}"
                            </div>
                        </div>

                        <button 
                            onClick={() => setSummary(null)}
                            className="w-full text-center text-xs text-gray-400 hover:text-gray-600 mt-4"
                        >
                            Dismiss Report
                        </button>
                    </div>
                </div>
            ) : (
                <div className="bg-gray-50 rounded-xl border-2 border-dashed border-gray-200 p-8 text-center h-64 flex flex-col items-center justify-center text-gray-400 sticky top-6">
                    <svg className="w-12 h-12 mb-2 opacity-50" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" /></svg>
                    <p className="text-sm font-medium">AI Leader's Guide</p>
                    {!isProgramComplete ? (
                         <p className="text-xs mt-2 max-w-[200px]">Waiting for the full program (Start & End Prayer) to be submitted.</p>
                    ) : (
                         <p className="text-xs mt-2">Program is complete! Click "Guide Me" to generate.</p>
                    )}
                </div>
            )}
        </div>
      </div>
    </div>
  );
};

export default AdminDashboard;